  version: '3.0'

  services:
    db:
      image: postgres:13
      container_name: appointmentSchedulingDB
      environment:
        POSTGRES_DB: appointmentScheduling
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:54332"

    app:
      image: appointment-backend
      container_name: appointmentSchedulingApp
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appointmentScheduling
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: root
        JWT_SECRET: uma_chave_secreta_segura

  volumes:
      postgres-data:
