version: '3.0'

services:
  db:
    image: postgres:13
    container_name: appointmentSchedulingDB
    environment:
      POSTGRES_DB: appointmentScheduling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:54332"

  app:
    image:


